{
 "title": "Demo Dashboard",
 "time": { "from": "2025-03-15T10:50:37.277Z", "to": "2025-03-15T11:34:05.751Z" },
 "panels": [
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT value\nFROM \"battery\" \nGROUP BY \"location\", \"station\"\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT value\nFROM \"humidity\" \nGROUP BY \"location\", \"station\"\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT value\nFROM \"temperature\" \nGROUP BY \"location\", \"station\"\nORDER BY time DESC"
    }
   ]
  }
 ]
}