version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # MQTT default port
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro


  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mosquitto
      - influxdb
  
  influxdb:
    image: influxdb:1.8
    ports:
      - 8087:8086
    volumes:
      - ./influxdb/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - type: bind
        source: influxdb/persistent/influxdb
        target: /var/lib/influxdb